### ISSUE TITLE
Dlanor Rants

### ISSUE THREAD

**Issue by ctom42** [07th-mod/umineko-answer#22]
I just went through all 3 Dlanor rants with all the latest files. There were small issues with each of them.

1st rant (Episode 5 middle): This one was mostly fine, but there needs to be a little more pause between the final three lines, they occasionally cut each other off. I'm not entirely sure why it only happens sometimes, but they are always pretty close together compared to the Umitweak version anyway.

2nd rang (Episode 5 end): Not sure why I didn't notice this one when I first reported issues with it, but there are issues with textwrapping mid-word. Additionally, the text automatically advances as soon as the last line finishes, and it is cleared almost instantly. There needs to either be a longer pause or a manual advancement.
![dlanor desu](https://user-images.githubusercontent.com/2365513/34930971-2dd6cb80-f99a-11e7-8746-447bf0f6a434.png)

Also, both the 1st and 2nd rant were had centered text in Umitweak. I'm not sure if the left aligned text is necessarily a problem, but it certainly looks odd to me. That might just be because I'm used to it centered though.

3rd rant (Episode 6): The voice lines in the middle cut each other off. This one is consistent and happened every time I tried it. I compared it to Umitweak just to double check the voice lines were indeed being cut off, and they were.

**Comment by KyuuGryphon** [comment]
Interestingly, in the case of Dlanor's second rant, the mid-word line breaks appear to be intentional - that's actually how they're split in the original script. It's definitely more jarring with the wider aspect ratio, though.

**Comment by drojf** [comment]
hmmm...I don't know why but the steam version deliberately put line breaks in the middle of the 'finished' part fro the second rant, but the umtweak version did not (left is our current script, right is the umitweak script):

![image](https://user-images.githubusercontent.com/1249449/34966632-58ac070e-fab1-11e7-90ad-63c99b559b44.png)

I'm working through the rest of the issues atm.

**Comment by drojf** [comment]
Just to directly show what  Kyuu Gryphon said: Left is our script, right is umitweak script for the 2nd rant.
![image](https://user-images.githubusercontent.com/1249449/34966927-8cc7cc60-fab3-11e7-93f9-7da572826f88.png)

1st rant (Episode 5 middle): This one was mostly fine, but
 
- there needs to be a little more pause between the final three lines, they occasionally cut each other off. **fixed by matching the umitweak delay/extending the delay**

2nd rant (Episode 5 end): 

- but there are issues with textwrapping mid-word. **Not fixed - I dunno whether to fix it since as KyuuGryphon said, it looks like they've deliberately added it in when they revised the script for the MG release, maybe to give that 'broken / glitchy' look**

- Additionally, the text automatically advances as soon as the last line finishes, and it is cleared almost instantly. There needs to either be a longer pause or a manual advancement. **added a longer pause - for reference, the umitweak version used manual advancement**

- Also, both the 1st and 2nd rant were had centered text in Umitweak. I'm not sure if the left aligned text is necessarily a problem, but it certainly looks odd to me. That might just be because I'm used to it centered though. **made sure text is centered in all three rants**

3rd rant (Episode 6): 
- The voice lines in the middle cut each other off. **fixed by increasing delay - I actually never reviewed this one before...**

----

I've attached a test script which goes through the three rants - Start a new game from episode 5 without using the subchapter select. You don't need any other files - but keep a backup of your current script.
[test script download](https://github.com/07th-mod/umineko-answer/files/1633348/desu.zip)

Please try it out for me - if you think it's OK i'll commit it

**Comment by drojf** [comment]
I'll consider this closed as I haven't had any reports about it for a while
