### ISSUE TITLE
Text error at portraits

### ISSUE THREAD

**Issue by Jellefishh** [07th-mod/umineko-answer#26]
In chapter 6, after the first twilight there is some incorrect text about the location of the bodies. The corpses of Rosa and Maria should be in the Parlor, not in the locations as seen in the screenshots.

<img width="1440" alt="rosa wrong location" src="https://user-images.githubusercontent.com/35735649/35284322-c8b5093e-005a-11e8-985a-0e107648fb15.png">
<img width="1440" alt="maria wrong location" src="https://user-images.githubusercontent.com/35735649/35284327-cb3264c2-005a-11e8-8d0b-618a585fabb7.png">

**Comment by drojf** [comment]
This should be fixed in the v1.1.0 release: https://github.com/07th-mod/umineko-answer/releases/tag/v1.1.0

Specificically, download this graphics patch: https://github.com/07th-mod/resources/releases/download/Bern/UminekoChiru-Update-v1.zip and check the folder `en\bmp\r_click\text\cha\ep6` - the text images should have been updated
