### ISSUE TITLE
Is there a graphic patch for the Mac?

### ISSUE THREAD

**Issue by erst0913** [07th-mod/umineko-answer#28]
i have seen people play the game with the ps3 graphics but i have seen that only the voices are ready so i was wondering its there a graphic patch for the mac? i want to play the answer arc but not having the ps3 backgrounds lowers the quality of the experience for me a lot.

**Comment by irlPM** [comment]
Yes it is already done. You can check those in the Umineko Wiki.

**Comment by drojf** [comment]
specifically here: https://github.com/07th-mod/guide/wiki/Umineko-Part-1---Voice-and-Graphics-Patch

I heard some people had problems with the automatic installer on Mac, if you decide to use /are capable of trying the automatic installer, let me know if you have problems. Otherwise just install manually.

**Comment by erst0913** [comment]
i had some problems trying to unzip the graphics, i cant use winzip and i dont have winrar to unzip the archive and when i try others uncompressing apps it doesn't work and says it isn't compatible. I didnt had to uncompress the graphics of the question arc because when i downloaded them they where already uncompressed same with all the other content of the questions arc i was wondering what could i do in this situation?

when i downloaded the files for the question arc they came like this
<img width="959" alt="captura de pantalla 2018-01-29 a la s 1 01 13 a m" src="https://user-images.githubusercontent.com/34149745/35495680-1f40c6a6-0490-11e8-80c6-a9b92408e13c.png">
<img width="558" alt="captura de pantalla 2018-01-29 a la s 1 01 28 a m" src="https://user-images.githubusercontent.com/34149745/35495707-37f47062-0490-11e8-8463-674879ba59c6.png">
<img width="665" alt="captura de pantalla 2018-01-29 a la s 1 01 37 a m" src="https://user-images.githubusercontent.com/34149745/35495709-3a5efda4-0490-11e8-9792-49dbe74db463.png">

**Comment by drojf** [comment]
Try this for mac: http://www.kekaosx.com/en/ . It will let you unzip the .7zip files.

**Comment by erst0913** [comment]
i tried using kaka to uzip but i get error 2 and the file doesn't unzip. Is there a way i can download the files already unzipped?

**Comment by drojf** [comment]
Can you get on our discord? I think it will be easier to debug that way.... : https://discord.gg/acSbBtD

**Comment by drojf** [comment]
Otherwise, following these instructions should work:


Open a terminal and copy paste this to install brew:

`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

run this command in the command line to install p7zip

`brew install p7zip`

run this command in the command line to install aria2

`brew install aria2`

now, put all your downloaded files together in one folder. Also place the following script in the same folder (unzip it first so you get a .sh file): 
[download_only.zip](https://github.com/07th-mod/umineko-answer/files/1677102/download_only.zip)

Finally, run the `download_only.sh` script file (make sure it is in the folder with all the other files). It will verify your downloads are OK and download any missing pieces. After the download it will try to extract the files. If the script fails during download, just run it again.

**Comment by erst0913** [comment]
added you on discord.

**Comment by drojf** [comment]
I sorted this out with OP, there were some issues with OP's command line. 

If you are having similar issues, here's a reliable manual install procedure:

- download [keka](http://www.kekaosx.com/en/) for extracting the archives
- download aria2c from here: https://github.com/aria2/aria2/releases/download/release-1.33.0/aria2-1.33.0-osx-darwin.tar.bz2 (if macosx can't open, use keka to unzip. Navigate to the 'bin' folder to get the executable file, should be called 'aria2c')
- extract aria2c to a folder, then open a Terminal in that same folder and run `aria2c --file-allocation=none --continue=true --max-concurrent-downloads=1 https://github.com/07th-mod/umineko-answer/raw/master/0.utf` to get the verified install files (may need to run repeatedly)
- unzip the archives manually
- download the mac patched .app file https://github.com/07th-mod/resources/releases/download/Bern/Umineko5to8_for_MacOSX.zip and extract it
- copy everything to the game directory
- run the new .app
