### ISSUE TITLE
Graphic and Text bugs in Chapter 7

### ISSUE THREAD

**Issue by ctom42** [07th-mod/umineko-answer#33]
I only checked the final scene so far, but I found a few problems.

First, there were 3 instances of the cutting through the black BG effect being not the right resolution. I have screencapped the lines immediately following them.

![cut1](https://user-images.githubusercontent.com/2365513/35762819-786af2da-086c-11e8-8b12-7290c91b79e2.png)
![cut2](https://user-images.githubusercontent.com/2365513/35762820-79ed15ac-086c-11e8-933b-d7cb38d6faa3.png)
![cut3](https://user-images.githubusercontent.com/2365513/35762821-7b54e618-086c-11e8-9d7a-ca6153ab39e3.png)

Additionally, during the golden petal scene, there were two bits where the text wrap was messed up.

![textline1](https://user-images.githubusercontent.com/2365513/35762860-1e260cdc-086d-11e8-9c8a-59f4de71d09a.png)
![textline2](https://user-images.githubusercontent.com/2365513/35762862-1fbbb79a-086d-11e8-8197-c00e91cc1c93.png)

Edit: for reference I am using the current public release, except I updated my 0.utf just before reading this segment.

**Comment by drojf** [comment]
Should be fixed in e3bf8191542f8146cbb661075b803543568e4a74 ,  but you need new images to fix the 'cut' scene. 

- The new images can be be found here: [Images Link](https://github.com/07th-mod/umineko-answer/files/1691453/cut_golden_snow_images.zip) 
- Latest Script: https://github.com/07th-mod/umineko-answer/blob/master/0.utf

When you unzip the files, use the directory structure in the zip file and copy into your game directory. It should overwrite 6 files.

**Comment by drojf** [comment]
This should be fixed now.
