### ISSUE TITLE
Misc Episode 8 Problems (sprites etc)

### ISSUE THREAD

**Issue by VLF100** [07th-mod/umineko-answer#35]
In some scenes, the sprites of certain characters basically didnt appear even you could hear their voices. Those scenes were:
- After Ange has entered the mansion following the cat, the scene changes back to all the faimily and co talking, several sprites missing. No screenshots of this sry.
- When the family is faking the argument in the golden land. All the characters talk one after another and they are all missing sprites until Gohda-Kinzo-Genji appear. I have noticed this is a bit random as when I replayed the scene some sprites which I didnt see the first time appeared. Screenshots:
[20180203105830_1](https://user-images.githubusercontent.com/24494940/35766130-404adbe8-08d2-11e8-826c-fd075df7b6d7.jpg)
[20180203105845_1](https://user-images.githubusercontent.com/24494940/35766131-41dba41a-08d2-11e8-8da9-ffc19c6f06f5.jpg)

**Comment by drojf** [comment]
thanks, I think i've identified the problem, i'm seeing how I can fix it now (for the whole script)....

**Comment by drojf** [comment]
I'll leave this open incase there are any other similar issues or issues created during my fix. I have gone and manually reviewed the sections my script touched, but still possible i missed something. 

You can tell you have this issue as this only happens when characters are displayed not at the usual "left, right, center" positions. So if more than 3 characters appear on the screen and there's a graphical bug as well, it's likely related to the way I fixed this issue.

The fix only required changes to the script file (0.utf), no new assets required.

**Comment by drojf** [comment]
Reported on discord (not related to the above but I thought i'd put all ep8 graphics problems here):

- In episode 8, during Bern's trial, when you choose the culprits, Mangagamer pachinko Battler appear instead of the ps3 sprite (Lucasilvz)

- Oh yeah, on the trial also when you select a character to see their statements, their steam sprites appear on the background faintly. (Valkyrio100)

edit: should be fixed in https://github.com/07th-mod/umineko-answer/commit/6fabf88cdc91b7ba1d0b1042fb759d2e5b7f79d6

**Comment by drojf** [comment]
This should be fixed now.
