### ISSUE TITLE
Accessing the volume menu causes the current line of text to disappear

### ISSUE THREAD

**Issue by andOlga** [07th-mod/umineko-answer#52]
Accessing the "Volume" menu from the right-click section will cause the currently displayed text to disappear from the screen and not even show up in the backlog when you return to the game. This is consistent, i.e. it happens every time. Here's a before/after comparison:

![image](https://user-images.githubusercontent.com/462484/50608625-38cd0680-0ede-11e9-939e-974f90cf08b0.png)
![image](https://user-images.githubusercontent.com/462484/50608661-5601d500-0ede-11e9-83a5-f153ab3fcc09.png)

And here's the empty backlog:
![image](https://user-images.githubusercontent.com/462484/50608680-62862d80-0ede-11e9-9531-03efa1c1d705.png)

- My operating system is Windows
- I installed the game very recently, a few days ago
- I am running the full patch
- I installed the game using the Automatic Installer

**Comment by drojf** [comment]
Because the menu uses the 'text' mode to display the menu, it clears the current text on the screen (it uses the game engine's built in "choose an option" function to make choices in visual novels).

As far as I understand it, I can't fix this without making my own custom menu like the game does (with sprite buttons for each option). I don't really want to do this since you don't interact with this menu very often. 

For now I will mark this as won't fix, but it's more like "I don't know how to fix it easily". I should really make a list of 'known bugs' on the wiki, so you know what to expect with certain things in the game.

If I discover an easy way to fix it while i'm doing something else, i'll definitely try to fix it though.

**Comment by drojf** [comment]
I figured out a way to fix it somewhat easily (I save the currently displayed text before you enter that menu), but for some reason the text log is still broken. I haven't pushed the changes yet, am just testing it on the 1080p question arcs for now.

**Comment by drojf** [comment]
for reference, I think this was fixed for the question arcs in https://github.com/07th-mod/umineko-question/commit/c378ba9e1452e77396e34c96f6347f63a2bdcf9b
it does appear to fix the backlog too

it hasn't yet been applied to the answer arcs normal/adv mode

**Comment by drojf** [comment]
This should be fixed in NVL mode by: 599aceed7c811f09b58f324d82526b45b675047e
In the answer arcs, I cherry picked the same fix in: 7eb0cb52a0b478cefe1d04d3be9759deb84f2feb

However I noticed that there was a bug in the mod menu where it would always re-display in ADV mode, even if it was previously in NVL mode. This would cause the text to go off the screen.

So I added a variable to keep track of NVL/ADV mode, and then restore the correct mode after exiting the mod menu in the following commits:

- f254b8c11533a209b01673deb19bf8a46f6614b7
- fb669fc372f0a09ea400c6889bc0b176bdc5f049
- 69902b3f9d29875327b92637cffdf3ccbcc3d1bc

Hopefully this fixes any bugs related to exiting the mod menu.

edit: Also fixed in question arcs in commits from https://github.com/07th-mod/umineko-question/commit/ffd6212734d7228db8543603084e73f749e5df17 to https://github.com/07th-mod/umineko-question/commit/e554252405c1b7291bc3c6de95f5917936f95ca8
