### ISSUE TITLE
Strange brown box in episode 7

### ISSUE THREAD

**Issue by andOlga** [07th-mod/umineko-answer#53]
This shows up every time when there's "X years until the incident":

![brown-box](https://user-images.githubusercontent.com/462484/51712723-bf3db980-2040-11e9-8643-422378db92dd.png)

The actual text, "X years until the incident" is wrapped in a strange dark-brown rectangle and is entirely off-centre within that rectangle. Some people have told me that they cannot see it, so I have played with saturation and lightness to better illustrate what is actually going on:

![brown-box-bright](https://user-images.githubusercontent.com/462484/51712787-f0b68500-2040-11e9-9bf2-7af559cf81fe.png)

Every other screen like this just uses a plain black background, so this should as well.

**Comment by drojf** [comment]
I measured the color values in your first image. The 'black' area is value [0,0,0]. and the 'brown' area is [5,2,2].

The reason I measured it is because, on my monitor, the brown area is only _just_ visible. This leads me to believe that this is a problem during editing the image, which wasn't caught because it couldn't be seen easily on the monitor.

HOWEVER, I'm guessing it can be easily seen on your monitor due to your monitor either not being calibrated correctly, or perhaps you have a special monitor where it's easier to see small color differences (like...a wide gamut monitor in 'stretch colors' mode). If you know the specifics of your monitor (TN or IPS/VA panel, cheap laptop monitor or expensive desktop monitor etc.) it would help confirm my theory. 

This seems like a pretty easy issue to fix anyway, just that someone needs to get around to doing it :S. I'll put it on low priority for now since I don't think that many users will notice it.

**Comment by ItaloKnox** [comment]
Just to give my two cents, I own a IPS that is properly calibrated and I could barely notice it. Might be easier if the image was bigger, but still a hard one to catch. At first, I even thought it was the black reflecting something from my background. lol

**Comment by andOlga** [comment]
I don't consider my montior to be "special". And I agree that the box is not strongly visible, but I just happened to notice it and now I cannot unsee it -- it *exists*. The model is Samsung C24F390FHI, which is a TFT monitor. It's connected over HDMI to a NVIDIA GTX 1050, and it's operating in "Normal" HDMI black level. The video card is configured to output RGB in full dynamic range -- in other words, the settings are pretty standard.

**Comment by drojf** [comment]
I switched computer (from my laptop to my desktop) and I can see it pretty easily...I'll go fix it

**Comment by drojf** [comment]
I noticed some other images in the `en\bmp\background\efe` had the same issue, and fixed them up too. The fixed images (haven't been uploaded yet) are  below:

![years_1998](https://user-images.githubusercontent.com/1249449/51717934-0191e580-2097-11e9-80db-11e807dfc360.png)
![oct_5_1985](https://user-images.githubusercontent.com/1249449/51717935-0191e580-2097-11e9-9108-f71579a4944c.png)
![oct_6_1986](https://user-images.githubusercontent.com/1249449/51717937-022a7c00-2097-11e9-852b-f4e7dc50abae.png)
![text13](https://user-images.githubusercontent.com/1249449/51717938-022a7c00-2097-11e9-8fd8-a7435bdd7032.png)
![years_1980](https://user-images.githubusercontent.com/1249449/51717939-02c31280-2097-11e9-9c71-63ec7149c124.png)
![years_1981](https://user-images.githubusercontent.com/1249449/51717940-02c31280-2097-11e9-9d3d-69fa708d9e9a.png)
![years_1982](https://user-images.githubusercontent.com/1249449/51717941-035ba900-2097-11e9-8fb5-2d995bd14ba3.png)
![years_1983](https://user-images.githubusercontent.com/1249449/51717943-035ba900-2097-11e9-8177-8c6153cbdef4.png)
![years_1984](https://user-images.githubusercontent.com/1249449/51717946-03f43f80-2097-11e9-9460-6c0b1ca2264b.png)
![years_1985](https://user-images.githubusercontent.com/1249449/51717947-03f43f80-2097-11e9-92a5-858789341c37.png)

**Comment by drojf** [comment]
[fix_answer_text_squares.zip](https://github.com/07th-mod/umineko-answer/files/2794216/fix_answer_text_squares.zip)

to be merged with the update zip along with any other changes
