### ISSUE TITLE
Mod installer

### ISSUE THREAD

**Issue by mionsonozaki** [07th-mod/umineko-answer#57]
hey! this is probably a super dumb question but i am really confused and i have no clue how to make it work

so im trying to install the mod for the umineko answer arc through the installer. (im on MacOS) after having some trouble locating the steam folder, i finally did and clicked on the Umineko5to8.app

unfortunately everytime i try to click on it to let the mod install, i get an error that says this:
"Can't install the mod to the path
/Users/username/Library/Application Support/Steam/steamapps/common/Umineko Chiru/Umineko5to8.app"

the install command says this:
('Path INVALID:', '/Users/username/Library/Application Support/Steam/steamapps/common/Umineko Chiru/Umineko5to8.app')

i cant select any other file in that folder either, only the Umineko5to8.app and i dont think i can access the folder through any other way. the game starts up normally as well whenever i click on the Umineko5to8.app outside of the mod installer. i really dont have a clue what im doing wrong so i hope you guys can help me :(

**Comment by drojf** [comment]
Sorry, I think it's my fault (a bug in the installer). In the mean time, can you try to select the `Umineko5to8.exe` or `Umineko` file instead (I know it's for windows, but by doing so you might trick the installer into installing)?

It should be in the same folder, eg `/Users/username/Library/Application Support/Steam/steamapps/common/Umineko Chiru/Umineko5to8.exe`

----
Reminder for myself to fix the bug:

I use this check so that when you select a file, it actually returns the parent path
```python
if not os.path.isdir(gameExecutablePath):
    gameExecutablePath= os.path.normpath(os.path.join(gameExecutablePath, os.pardir))
```

However Umineko5to8.app might be treated as a folder, so instead of returning the parent path, it returns the folder itself.

**Comment by drojf** [comment]
I *think* I've fixed this now - if you re-download the installer you shouldn't have that bug anymore: https://github.com/07th-mod/python-patcher/releases/latest

If you still get the bug, try the workaround in the previous comment and let me know

**Comment by drojf** [comment]
I'm going to close this issue now - If you have further issues please report them on this issue in the `python-patcher` repository:

https://github.com/07th-mod/python-patcher/issues/29
